root@ec25add1092f:/workspace/MotionVectorization# ./scripts/script.sh videos/hassan.txt
videos/hassan.txt
PREPROCESS
hassan
RAFT
hassan
0it [00:00, ?it/s]
videos/hassan.txt
CLUSTER
hassan
Configs:
  video_file:   hassan
  video_dir:    videos
  output_dir:   outputs
  start_frame:  0
  max_frames:   100
  bg_file:      None
  bg_thresh:    0.1
  lo_thresh:    30
  hi_thresh:    100
  max_radius:   3
  add_contrast: False
  link: False
  min_cluster_size:     30
  min_density:  0.15
  min_dim:      5
  config:       motion_vectorization/config/hassan.json
  blur_kernel:  1
  min_opt_size: 32
  use_gpu:      True
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/extract_clusters.py", line 189, in <module>
    main()
  File "/workspace/MotionVectorization/motion_vectorization/extract_clusters.py", line 114, in main
    frame_idx = frame_idxs[0]
                ~~~~~~~~~~^^^
IndexError: list index out of range
TRACK
Logging to motion_vectorization/logs/hassan_track_20327.out
TIME: 2025-09-10 09:56:38.471348
Configs:
  video_file:   hassan
  video_dir:    videos
  output_dir:   motion_vectorization/outputs
  suffix:       None
  config:       motion_vectorization/config/hassan.json
  max_frames:   100
  start_frame:  0
  base_frame:   0
  min_cluster_size:     30
  min_density:  0.15
  bg_file:      None
  main_match_thresh:    0.6
  single_match_thresh:  0.2
  num_match_shapes:     5
  fallback_match_thresh:        0.6
  drop_thresh:  0.05
  breaks:       []
  multiply:     False
  all_joint:    False
  manual_init:  False
  hungarian:    False
  min_opt_size: 32
  blur_kernel:  1
  lr:   0.01
  p_weight:     0.1
  n_steps:      50
  use_gpu:      True
  bleed:        50
  overlap_thresh:       0.9
  use_k:        False
  use_r:        False
  use_s:        False
  use_t:        False
  init_r:       False
  init_s:       False
  init_t:       False
  verbose:      True
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/extract_shapes.py", line 1527, in <module>
    main()
  File "/workspace/MotionVectorization/motion_vectorization/extract_shapes.py", line 241, in main
    frame_idx = dataloader.frame_idxs[t]
                ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
OPTIM
Logging to motion_vectorization/logs/hassan_optim_3729.out
2025-09-10 09:56:44.241340
Configs:
  video_file:   hassan
  video_dir:    videos
  output_dir:   outputs
  suffix:       None
  config:       motion_vectorization/config/hassan.json
  date: None
  frame_rate:   24
  subsample_rate:       1
  max_frames:   100
  start_frame:  0
  scale:        0.3
  bg_thresh:    0.1
  min_cluster_size:     30
  median_radius:        5
  cluster_eps:  5
  cluster_min_samples:  10
  bg_file:      None
  init_weight:  0.0
  init_thresh:  0.01
  num_match_shapes:     5
  match_radius: 120.0
  main_match_thresh:    0.5
  fallback_match_thresh:        0.5
  match_method: hu
  min_opt_size: 32
  blur_kernel:  1
  lr:   0.01
  p_weight:     0.1
  use_z:        True
  n_steps:      50
  use_gpu:      True
  bleed:        50
  all_joint:    False
  overlap_thresh:       0.9
  manual_init:  False
  use_k:        False
  use_r:        False
  use_s:        False
  use_t:        False
  init_r:       False
  init_s:       False
  init_t:       False
  drop_thresh:  0.005
  snap_thresh:  3
  scale_thresh: 0.03
  angle_thresh: 5.0
  debug:        False
  verbose:      True
  show: False
  show_optim:   False
  show_recon:   False
  checkpoint:   False
device: cuda
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 757, in <module>
    main()
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 265, in main
    time_bank = pickle.load(open(os.path.join(video_folder, 'time_bank.pkl'), 'rb'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/hassan_None/time_bank.pkl'
PROGRAM
shapes_folder: motion_vectorization/outputs/hassan_None/shapes
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 187, in <module>
    main()
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 61, in main
    for filename in os.listdir(shapes_folder):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'motion_vectorization/outputs/hassan_None/shapes'
root@ec25add1092f:/workspace/MotionVectorization# 